name: docker-buildx-push

on:
  push:
    branches:
      - master

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: mxie/cloudflared
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and Publish Docker Images
        uses: zmingxie/docker_buildx@master
        with:
          publish: true
          tag: latest
          dockerFile: ./Dockerfile
          buildArg: VCS_REF=`git rev-parse --short HEAD`,CLOUDFLARED_VERSION='2020.2.0',BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
          platform: linux/amd64,linux/arm64,linux/arm/v7
          imageName: ${{ env.DOCKER_IMAGE_NAME }}
          dockerHubUser: ${{ secrets.DOCKER_LOGIN_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
