name: Build multi-arch Docker Images via buildx

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: mxie/cloudflared
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup dgoss
        uses: e1himself/goss-installation-action@v1
        with:
          version: 'v0.3.9'
      -
        name: Run Docker dev build
        run: |
          docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:local
          dgoss run --name cloudflared --rm -ti ${{ env.DOCKER_IMAGE_NAME }}:local
      -
        name: Build and Publish Docker Images
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          tag: latest
          dockerFile: ./Dockerfile
          platform: linux/amd64,linux/arm64,linux/arm/v7
          imageName: ${{ env.DOCKER_IMAGE_NAME }}
          dockerHubUser: ${{ secrets.DOCKER_LOGIN_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_LOGIN_PASSWORD }}
