name: pull_request_check

on:
  pull_request:
    branches:
      - master

jobs:
  docker-dgoss:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: mxie/cloudflared
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup dgoss
        uses: e1himself/goss-installation-action@v1
        with:
          version: 'v0.3.9'
      -
        name: Build dev image and check dgoss
        run: |
          docker build . --file Dockerfile --build-arg VCS_REF=`git rev-parse --short HEAD` --tag ${{ env.DOCKER_IMAGE_NAME }}:local
          dgoss run --name cloudflared --rm -ti ${{ env.DOCKER_IMAGE_NAME }}:local
